# Generated by Django 5.0.4 on 2024-05-16 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fot',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
