# Generated by Django 5.0.4 on 2024-05-16 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_fotografia_data_fot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='data_fot',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='fotda',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
