# Generated by Django 5.0.4 on 2024-05-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_remove_fotografia_data_fot_fotografia_fotda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='fotda',
            new_name='data_fotografia',
        ),
    ]
